all:
	${YAFFLE} --build prelude.ipkg

install:
	${YAFFLE} --install prelude.ipkg

install-with-src:
	${YAFFLE} --install-with-src prelude.ipkg

docs:
	${YAFFLE} --mkdoc prelude.ipkg

clean:
	$(RM) -r build
